### ISSUE TITLE
how does async commit max_commit_ts avoid schema change 

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/tidb#36875]
## General Question

Issue Number: https://github.com/pingcap/tidb/issues/20531

https://github.com/pingcap/tidb/pull/20550,

I have a question about  how does max_commit_ts can avoid schema change during a sql execution.

异步提交中，避免在sql执行过程中发生schema变更，流程为：
1. 计算currentTS = oracle.EncodeTSO(int64(time.Since(c.txn.startTime)/time.Millisecond)) + c.startTS 
2. 检查[startTs, currentTS] 是否schema 一致 
3.初始化 maxCommitTS = currentTS + safeWindow
4.执行2pc的 prewrite、commit
(其中上述3步中的 safeWindow 值为 2s.)

TiDB online schema 等待各个tidb 同步 schema 设置了同步时间为： waitTime := 2 * d.lease
从而保证了新的 scheme 变更在接下来等待的 waitTime 里一定会被各个 tidb 获取到。

举个极端的例子: 
事务提交计算的 currentTS 为 t1,
一条 ddl 执行 schema 变更(某个阶段)时间为 t2，其中 t2>t1,
online schema，保证了在[t2, t2+waitTime] 这个时间范围内，各个tidb都能获取到新的schema,这个时间点可能为 t2+0.00001s,也可能在 t2+waitTime-0.00001s

在上述异步提交2中: 检查 [startTs, currentTS] 是否schema 一致时候
   在 [startTs, t1] 里，schema 没有发生变更，通过

在3中：初始化 maxCommitTS = currentTS + 2
    成功设置了 maxCommitTS = t1 + 2s；(2s 是 safeWindow 值)

基于异步提交，假设最终计算的真正提交的min_commit_ts = max_commit_ts - 0.0000001，在[t1, max_commit_ts)范围都是合理的。

这里如果schema 变更的时间点是 t2 比 t1 只大了一点点，例如 t2 = t1 + 0.000001，
那么显然 min_commit_ts > t2 的；

这样就出现了 tidb 执行这个事务 sql 时候，是基于 t2 之前的 schema 组织数据，但是事务的提交 commitTs(最终的min_commit_ts) > t2,那么在事务提交时候，发生了schema变化呀。

就是说: t1 < t2 < commitTs < t1 + 2
在 [ts, ts+2] 这里发生了 schme 变更，变更时间为 t2.

在正常非异步提交的2pc中：
1. prewrite 数据
2. get commitTs from pd
3. 检查 [startTs, commitTs) 之间是否发生 schema 变更，如果有变更就报错

在这里就可以保证执行这个事务 sql 和提交事务都是基于相同的 schema 的。

我的问题是：对比异步提交的 maxCommitTS，没看明白如何保证这一点的。

Poor English:

async commit case，the step to avoid schema change during trasaction like these：
1. calculate currentTS = oracle.EncodeTSO(int64(time.Since(c.txn.startTime)/time.Millisecond)) + c.startTS
2. check schema during [startTs, currentTS] not change
3. init maxCommitTS = currentTS + safeWindow
4. go on 2pc: prewrite、commit
(step 3 above, safeWindow is set 2s)

TiDB online schema wait all tidb servers get the new schema change, waitTime := 2 * d.lease; the all tidb servers will get the new shema, otherwise it will core down.

I have a questionlike a case here:
1. a txn get currentTS = t1,
2. a concurrency ddl is ongoing, schema change(some state like StateWriteOnly、StateDeleteOnly or else) time on t2, and t2>t1

online schema guarantee, during time range [t2, t2+waitTime], all tidb servers get the new schema state.For example, a tidb server can get it at t2+0.00001s, can also at t2+waitTime-0.00001s.

the async commit step:
2. check schema during [startTs, currentTS] not change
   because during [startTs, t1], schema not change，it passed
   
3. init maxCommitTS = currentTS + safeWindow
   it set maxCommitTS = t1 + 2s；(2s is the safeWindow)

2pc process:
1. it then prewrite data, and calculate then eventual, min_commit_ts = max_commit_ts - 0.0000001, actually, commitTs in range [t1, max_commit_ts) is all ok.
2. it then commit data, use  min_commit_ts = max_commit_ts - 0.0000001 as commitTs.

However, t2 is greater than t1 just a very small value,for example, t2 = t1 + 0.000001; 
then, in this case will be: min_commit_ts > t2

the problem is:
tidb execute sql use the schema before t2(old schema); but commit use a commitTs after t2(new schema time). 

that is: t1 < t2 < commitTs < t1 + 2
so during the txn exection, schema changed.

In normal 2pc process：
1. prewrite 
2. get commitTs from pd
3. check during [startTs, commitTs) schema not changed

It guarantees the txn execution use the same schema.
My question is：Make a comparison, async commit use maxCommitTS, i do not understand how it guarantee a txn use the same schema.

**Comment by yudongusa** [comment]
@jiyfhust to make it easy for global contributors and users to understand the issues, would you mind to rephrase the problem in English? Appreciate your understanding and collaboration!

**Comment by jiyfhust** [comment]
> 

done

**Comment by jiyfhust** [comment]
> @jiyfhust to make it easy for global contributors and users to understand the issues, would you mind to rephrase the problem in English? Appreciate your understanding and collaboration!

@yudongusa  done

**Comment by tiancaiamao** [comment]
PTAL @sticnarf

**Comment by sticnarf** [comment]
You're right, the max_commit_ts mechanism does not fully solve the schema problem. We don't prevent all schema version changes during the commit of an async commit problem.

Instead, we try to solve the worst cases. We try to make sure no incompatible data will appear due to the commit of an async commit transaction with an old schema.

So, the sleep happens before executing the write reorg (and other cases like constriant checks). Transactions using a schema earlier than "write only" will either fallback because of the max_commit_ts check or visible to the reorg process.

**Comment by jiyfhust** [comment]
hi @sticnarf , is there some relationship between SchemaLease and safeWindow?

with safeWindow = 2 * SchemaLease, an async commit transaction could across only one schema change, i think this is what online ddl needs.

The SchemaLease default value is 1s，and safeWindow is 2s, this is ok.

https://github.com/pingcap/tidb/blob/ba9aa67bc2aff9a06fcd066b6d2afbea44ae1f85/session/tidb.go#L109
    	// schemaLease is the time for re-updating remote schema.
	// In online DDL, we must wait 2 * SchemaLease time to guarantee
	// all servers get the neweset schema.
	// Default schema lease time is 1 second, you can change it with a proper time,
	// but you must know that too little may cause badly performance degradation.
	// For production, you should set a big schema lease, like 300s+.
	schemaLease = int64(1 * time.Second)

what if we change SchemaLease with a time less than 1s？ with safeWindow = 2s is it will be a problem?

is there a requirment like this: safeWindow <  waitTime(2 * SchemaLease)?

like a series schema change schema0, schema1, schema2:
1. current schema is schema0
2. a transion txn1 in tidb-0 start
3. schema change on tidb-1, with schema1
4. tidb-0 have not syncer the newest schema schema1, now it is still schema0, and  txn1 begins async commit
5. after schema1 waitTime, schema change with schema2
7. if safeWindow > waitTime, there will be a possibility txn1 get a commit ts > schema2(ts)

then txn1 with schema0 start, and commit with ts > schema2(ts), it accorss schema0、schema1、schema2, is it will be a problem not satisfy F1 Online Schema Change(not just add index case)？

**Comment by jiyfhust** [comment]
hi @sticnarf , is there some relationship between SchemaLease and safeWindow?

with safeWindow = 2 * SchemaLease, an async commit transaction could across only one schema change, i think this is what online ddl needs.

The SchemaLease default value is 1s，and safeWindow is 2s, this is ok.

https://github.com/pingcap/tidb/blob/ba9aa67bc2aff9a06fcd066b6d2afbea44ae1f85/session/tidb.go#L109
    	// schemaLease is the time for re-updating remote schema.
	// In online DDL, we must wait 2 * SchemaLease time to guarantee
	// all servers get the neweset schema.
	// Default schema lease time is 1 second, you can change it with a proper time,
	// but you must know that too little may cause badly performance degradation.
	// For production, you should set a big schema lease, like 300s+.
	schemaLease = int64(1 * time.Second)

what if we change SchemaLease with a time less than 1s？ with safeWindow = 2s is it will be a problem?

is there a requirment like this: safeWindow <  waitTime(2 * SchemaLease)?

like a series schema change schema0, schema1, schema2:
1. current schema is schema0
2. a transion txn1 in tidb-0 start
3. schema change on tidb-1, with schema1
4. tidb-0 have not syncer the newest schema schema1, now it is still schema0, and  txn1 begins async commit
5. after schema1 waitTime, schema change with schema2
7. if safeWindow > waitTime, there will be a possibility txn1 get a commit ts > schema2(ts)

then txn1 with schema0 start, and commit with ts > schema2(ts), it accorss schema0、schema1、schema2, is it will be a problem not satisfy F1 Online Schema Change(not just add index case)？
