### ISSUE TITLE
planner: plan replayer cannot work with views

### ISSUE THREAD

**Issue by jansu-dev** [pingcap/tidb#38853]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
this case seems the same as https://github.com/pingcap/tidb/issues/36712 , sort of.

```
>use test
Database changed
>CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, c1 INT NOT NULL);
Query OK, 0 rows affected (0.10 sec)

>INSERT INTO t1 (c1) VALUES (1),(2),(3),(4),(5);
Query OK, 5 rows affected (0.02 sec)
Records: 5  Duplicates: 0  Warnings: 0

>CREATE VIEW v1 AS SELECT * FROM t1 WHERE c1 > 2;
Query OK, 0 rows affected (0.09 sec)

>SELECT * FROM t1;
+----+----+
| id | c1 |
+----+----+
|  1 |  1 |
|  2 |  2 |
|  3 |  3 |
|  4 |  4 |
|  5 |  5 |
+----+----+
5 rows in set (0.00 sec)

>SELECT * FROM v1;
+----+----+
| id | c1 |
+----+----+
|  3 |  3 |
|  4 |  4 |
|  5 |  5 |
+----+----+
3 rows in set (0.01 sec)

>plan replayer dump explain SELECT * FROM v1;
+------------+
| File_token |
+------------+
|            |
+------------+
1 row in set (0.00 sec)

>select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v6.1.0 |
+--------------------+
1 row in set (0.00 sec)
```
### 2. What did you expect to see? (Required)
output a File_token

### 3. What did you see instead (Required)

```
>plan replayer dump explain SELECT * FROM v1;
+------------+
| File_token |
+------------+
|            |
+------------+
```
### 4. What is your TiDB version? (Required)
```
>select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v6.1.0 |
+--------------------+
1 row in set (0.00 sec)
```

**Comment by wxbty** [comment]
@jansu-dev  This problem does exist in v6.1.0 , but the latest master is normal, so there is no need to fix it?

**Comment by jansu-dev** [comment]
thx for your response.

1. This problem does exist in v6.1.0? Really? i don't think so.
![image](https://user-images.githubusercontent.com/76909042/199911516-d5e8bfb6-d58c-4fbe-b52a-c39a1058a53f.png)



2. The latest master is normal? --> yeah.   
i tested it just now. it's ok for v6.3.0 on mac m1.
    ```
    tiup playground v6.3.0 jan --db 1 --kv 1 --pd 1
    ```
    ![image](https://user-images.githubusercontent.com/76909042/199912482-d19382d9-0854-4232-b507-6934d3b00661.png)


3. Also, i upgraded the cluster version used ,when i submitted the issue, to v6.3.0.  normal.
![image](https://user-images.githubusercontent.com/76909042/199911004-dca803b1-3dad-4fc3-8584-073bd709d923.png)



seems that this problem already has been fixed.
or, could you help me check if https://github.com/pingcap/tidb/issues/36712 cased the problem? thx

**Comment by jansu-dev** [comment]
@wxbty  after that ,you could label the `duplicated`.i think🤔

**Comment by wxbty** [comment]
@jansu-dev   I used the code of pr 11 and updated it to v6.1.0, but the unit test still failed, indicating that this pr did not fix the current issue, it should be the code fix later

**Comment by jansu-dev** [comment]
yeah, it seems still have bug on v6.1.0. @wxbty

**Comment by wxbty** [comment]
@jansu-dev  Before v6.1.0, an error was reported when parsing the table name of the view, but the error message was hidden and converted, and only the empty string was displayed. The pr #37224 of  v6.1.0 added the judgment of the view

**Comment by Yisaer** [comment]
Hi @wxbty @jansu-dev 

This issue is duplicated with https://github.com/pingcap/tidb/issues/37163 , and plan replayer has supported view since https://github.com/pingcap/tidb/pull/37224  and supported since v6.3.0.
