### ISSUE TITLE
Different results from MySQL and tidb

### ISSUE THREAD

**Issue by qazbnm456** [pingcap/tidb#6092]
1. What did you do?
Execute the statement: `select 1, 2, 3 from dual union select * from t limit 1 offset 2;`.

2. What did you expect to see?
http://sqlfiddle.com/#!9/ce0a4a/1

3. What did you see instead?
![image](https://user-images.githubusercontent.com/6451933/37590921-b8696f1e-2ba4-11e8-9878-8ba252625a93.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v2.0.0-rc.1
Git Commit Hash: 4a52a6ae580224a62b2c17707e64720af26c88fd
Git Branch: release-2.0
UTC Build Time: 2018-03-09 02:12:41
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 1.1.0-dev.2
```

**Comment by winoros** [comment]
If there's no `order by` clause, we won't guarantee the return order of the row.

**Comment by zz-jason** [comment]
mysql seems have some bugs:
```sql
MySQL(localhost) > select 1, 2, 3 from dual union select * from t limit 1 offset 2;
+---+---+-----+
| 1 | 2 | 3   |
+---+---+-----+
| 2 | 6 | dog |
+---+---+-----+
1 row in set (0.00 sec)

MySQL(localhost) > select 1, 2, 3 from dual;
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
1 row in set (0.00 sec)

MySQL(localhost) > select * from t limit 1 offset 2;
+----+----+------+
| id | tn | type |
+----+----+------+
|  3 |  7 | duck |
+----+----+------+
1 row in set (0.00 sec)
```

**Comment by qazbnm456** [comment]
@winoros I don't actually get your point.
@zz-jason Yeah, that's the situation I met.
If I execute the statement in MySQL, it'll process the query like `((select 1, 2, 3 from dual union select * from t) limit 1 offset 2)`. Therefore, only one row returned.

However, tidb seems to process the query like `((select 1, 2, 3 from dual) union (select * from t limit 1 offset 2))`.

I don't know if this is a bug or feature toward MySQL, but this trick has been used by some security experts to bypass the limitation or something.
Ref:
1. [About Join --- SQLi](http://www.venenof.com/index.php/archives/240/)
2. [SQLi —— 逗号，空格，字段名过滤突破](http://drops.blbana.cc/2017/05/20/SQLi-%E2%80%94%E2%80%94-%E9%80%97%E5%8F%B7%EF%BC%8C%E7%A9%BA%E6%A0%BC%EF%BC%8C%E5%AD%97%E6%AE%B5%E5%90%8D%E8%BF%87%E6%BB%A4%E7%AA%81%E7%A0%B4/).

**Comment by qazbnm456** [comment]
@shenli Sorry, I don't think the issue has been resolved, could you reopen this?

The main question is the same query: `select 1, 2, 3 from dual union select * from t limit 1 offset 2;` giving different results from Tidb and MySQL, and it seems there's no consensus in this thread.

I would prefer getting the result given by MySQL, but I don't know if you have other thoughts regarding this?

**Comment by shenli** [comment]
@qazbnm456 I think this issue is clear enough.
In `select * from t limit 1 offset 2;`, there is no order by clause. So the database could return data in any order. It depends on the storage engine. Please refer to [this post](https://stackoverflow.com/questions/1949641/mysql-row-order-for-select-from-table-name).

So any single row from table t is the correct answer for `select * from t limit 1 offset 2;`. The answers from TiDB and MySQL are different but both right.

**Comment by qazbnm456** [comment]
Thanks for your clarification, but I'm not actually arguing the `select * from t limit 1 offset 2;` statement. I know the above query will return any single row from table `t` because I don't give the engine a clear hint.

The query I care more is the result of `select 1, 2, 3 from dual union select * from t limit 1 offset 2;`.

I'm just curious that does it mean executing `select 1, 2, 3 from dual union select * from t limit 1 offset 2;` will never return only one single row due to the implementation of TiDB's storage engine? Ａs a matter of fact, that one single returned row is the expected result to me of the query.

**Comment by shenli** [comment]
@qazbnm456 I got your point.
I read MySQL's [document](https://dev.mysql.com/doc/refman/5.7/en/union.html) and found that:
```sql
To apply ORDER BY or LIMIT to an individual SELECT, place the clause inside the parentheses that enclose the SELECT:

(SELECT a FROM t1 WHERE a=10 AND B=1 ORDER BY a LIMIT 10)
UNION
(SELECT a FROM t2 WHERE a=11 AND B=2 ORDER BY a LIMIT 10);
Note
Previous versions of MySQL may permit such statements without parentheses. In MySQL 5.7, the requirement for parentheses is enforced.

Use of ORDER BY for individual SELECT statements implies nothing about the order in which the rows appear in the final result because UNION by default produces an unordered set of rows. Therefore, the use of ORDER BY in this context is typically in conjunction with LIMIT, so that it is used to determine the subset of the selected rows to retrieve for the SELECT, even though it does not necessarily affect the order of those rows in the final UNION result. If ORDER BY appears without LIMIT in a SELECT, it is optimized away because it will have no effect anyway.

To use an ORDER BY or LIMIT clause to sort or limit the entire UNION result, parenthesize the individual SELECT statements and place the ORDER BY or LIMIT after the last one. The following example uses both clauses:

(SELECT a FROM t1 WHERE a=10 AND B=1)
UNION
(SELECT a FROM t2 WHERE a=11 AND B=2)
ORDER BY a LIMIT 10;
A statement without parentheses is equivalent to one parenthesized as just shown.
```

I agree the issue is not solved yet. I think we need to fix it in TiDB's parser yacc file.

**Comment by qazbnm456** [comment]
Close this due to https://github.com/pingcap/tidb/pull/6335.
